### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by mtmustski** [noahkw/gfypy#4]
I created a brand new api key setting the redirect uri to http://localhost:8000 and upon authenticating,
`gfypy = Gfypy(client_id, client_secret, 'gfypy_credentials.json')`
`gfypy.authenticate()`
 I received the following error 
>ValueError: dictionary update sequence element #0 has length 1; 2 is required.

I attached the full stack trace [error.txt](https://github.com/noahkw/gfypy/files/4784283/error.txt)

**Comment by noahkw** [comment]
Hi, 
this is actually an error in the documentation, thanks for pointing it out.
The redirect URI needs to be set to `http://localhost:8000/callback`. 

There was a bug with imports on the latest master branch so if you're using that, you should consider upgrading. If you're on v0.0.3 from PyPi, then you should be good.
